modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "findingfortunes"
version = "${version}"
displayName = "Finding Fortunes"
authors = "RedPxnda"
description = '''
A simple mod adding simple fortune cookies.
'''
#logoFile = ""

[[dependencies.findingfortunes]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.findingfortunes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.findingfortunes]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"